djangoProducts_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'djangoProducts_app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^success/', views.LoginSuccess.as_view(), name='success'),
    url(r'^register/', views.Register.as_view(), name='register'),
    url(r'^login/', views.login_user, name='login'),
    url(r'^register_user/', views.register_user, name='register_user'),
    url(r'^logout/', views.logout_user, name= 'logout'),
]

djangoProducts_settings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangoProducts_app.urls'), name='djangoProducts_app')

]

djangoProducts_app/models.py
from django.db import models

# Create your models here.

djangoProducts_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

class IndexView(TemplateView):
    template_name = 'djangoProducts_app/login.html'


class LoginSuccess(LoginRequiredMixin, TemplateView):
    template_name = 'djangoProducts_app/home.html'


class Register(TemplateView):
    template_name = 'djangoProducts_app/register.html'


def register_user(request):
    data = request.POST
    user = User.objects.create_user(
        username = data['username'],
        password = data['password'],
        email = data['email'],
        first_name = data['first_name'],
        last_name = data['last_name']
    )
    return login_user(request)


def login_user(request):
    data = request.POST
    username = data['username']
    password = data['password']
    user = authenticate(
        username = username,
        password = password
    )
    if user is not None:
        login(request = request, user = user)
    else:
        return HttpResponseRedirect(redirect_to='/')
    return HttpResponseRedirect(redirect_to='/success')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(redirect_to='/')

# def add_product(request)
#     p = product(
#         user = request.user
#         title = product['title'],

djangoProducts_app/templates/djangoProducts_app/home.html
{% extends 'tutorial_app/index.html' %}

{% block content %}
  <a href="{% url 'djangoProducts:logout' %}">Log Out</a>
  <div id="_giphy_tv"></div>
{% endblock %}

djangoProducts_app/templates/djangoProducts_app/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Products</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
  </head>
  <body>
    {% block content %}{% endblock %}
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
  </body>
</html>

djangoProducts_app/templates/djangoProducts_app/login.html
{% block content %}
  <h1>Login Existing User</h1>
  <form class="" action="{% url 'djangoProducts_app:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" value="" placeholder="Username">
    <input type="password" name="password" value="" placeholder="Password">
    <button type="submit" name="button">Submit</button>
  </form>
  <div class="">
    <p>Not a current user? Register <a href="{% url 'djangoProducts_app:register' %}">here</a></p>
  </div>
{% endblock %}

djangoProducts_app/templates/djangoProducts_app/register.html
{% block content %}
  <h1>Register New User</h1>
  <form class="" action="{% url 'djangoProducts_app:register_user' %}" method="post">
    {% csrf_token %}
    <input type="text" name="email" value="" placeholder="Email">
    <input type="text" name="username" value="" placeholder="username">
    <input type="password" name="password" value="" placeholder="Password">
    <input type="text" name="first_name" value="" placeholder="Enter First Name">
    <input type="text" name="last_name" value="" placeholder="Enter Last Name">
    <button type="submit" name="button">Submit</button>
  </form>

{% endblock %}